import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { supabase } from '../../services/supabase';

// ── Create Order ──
export const createOrder = createAsyncThunk(
  'orders/createOrder',
  async (orderData, { rejectWithValue }) => {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const user = session?.user;
      if (!user) throw new Error('Non authentifié');

      // Helper function for retries
      const withRetry = async (fn, retries = 3, delay = 1500) => {
        for (let i = 0; i < retries; i++) {
          try {
            return await fn();
          } catch (err) {
            if (i === retries - 1) throw err;
            if (err.message?.includes('fetch') || err.status === 0) {
              console.warn(`Attempt ${i + 1} failed, retrying in ${delay / 1000}s...`);
              await new Promise(r => setTimeout(r, delay));
              continue;
            }
            throw err;
          }
        }
      };

      // Calculate total
      const subtotal = (orderData.items || []).reduce(
        (sum, item) => sum + (item.price || 0) * (item.quantity || 1),
        0
      );
      const shippingCost = orderData.shippingCost || 0;
      const total = subtotal + shippingCost;

      // Create the order with retry
      const { data: order, error } = await withRetry(() =>
        supabase
          .from('orders')
          .insert({
            user_id: user.id,
            order_number: '', // Will be generated by trigger
            subtotal,
            shipping_cost: shippingCost,
            total,
            shipping_address: orderData.shippingAddress || {},
            payment_method: orderData.paymentMethod || 'cod',
            payment_status: 'pending',
            status: 'pending',
            notes: orderData.notes || null,
          })
          .select()
          .single()
      );

      if (error) throw error;

      // Create order items
      if (orderData.items && orderData.items.length > 0) {
        // Fetch product details to get vendor IDs
        const productIds = orderData.items.map((i) => i.productId);
        const { data: products } = await withRetry(() =>
          supabase
            .from('products')
            .select('id, name, images, vendor_id, stock')
            .in('id', productIds)
        );

        const productMap = {};
        (products || []).forEach((p) => { productMap[p.id] = p; });

        const orderItems = orderData.items.map((item) => {
          const product = productMap[item.productId] || {};
          return {
            order_id: order.id,
            product_id: item.productId,
            vendor_id: product.vendor_id || user.id,
            product_name: product.name || 'Produit',
            product_image: (product.images || [])[0] || null,
            quantity: item.quantity || 1,
            unit_price: item.price || 0,
            total_price: (item.price || 0) * (item.quantity || 1),
            status: 'pending',
          };
        });

        const { error: itemsError } = await withRetry(() =>
          supabase
            .from('order_items')
            .insert(orderItems)
        );

        if (itemsError) throw itemsError;

        // Decrease stock
        for (const item of orderData.items) {
          const product = productMap[item.productId];
          if (product && product.stock !== undefined) {
            try {
              await supabase
                .from('products')
                .update({ stock: Math.max(0, (product.stock || 0) - (item.quantity || 1)) })
                .eq('id', item.productId);
            } catch (stockError) {
              // Minor failure, don't block order
              console.warn('Failed to update stock:', stockError);
            }
          }
        }
      }

      // Fetch complete order with items
      const { data: completeOrder } = await withRetry(() =>
        supabase
          .from('orders')
          .select('*, order_items(*, product:products(id, name, images))')
          .eq('id', order.id)
          .single()
      );

      return { data: completeOrder || order };
    } catch (error) {
      console.error('Final CreateOrder Error:', error);
      return rejectWithValue(error.message || 'Impossible de passer la commande');
    }
  }
);

// ── Fetch Orders ──
export const fetchOrders = createAsyncThunk(
  'orders/fetchOrders',
  async (params = {}, { rejectWithValue }) => {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const user = session?.user;
      if (!user) throw new Error('Non authentifié');

      // Get user profile to check role
      const { data: profile } = await supabase
        .from('profiles')
        .select('role')
        .eq('id', user.id)
        .single();

      const { page = 1, limit = 10, status } = params;

      let query = supabase
        .from('orders')
        .select('*, order_items(*, product:products(id, name, images)), customer:profiles!orders_user_id_fkey(id, first_name, last_name, email)', { count: 'exact' });

      // Scope based on role
      if (profile?.role === 'vendor') {
        // Vendor: show orders that contain their products
        const { data: vendorOrderIds } = await supabase
          .from('order_items')
          .select('order_id')
          .eq('vendor_id', user.id);

        const orderIds = [...new Set((vendorOrderIds || []).map((o) => o.order_id))];
        if (orderIds.length === 0) {
          return { data: [], pagination: { page, limit, total: 0, totalPages: 0 } };
        }
        query = query.in('id', orderIds);
      } else if (profile?.role !== 'admin' && profile?.role !== 'superadmin') {
        // Client: only their orders
        query = query.eq('user_id', user.id);
      }
      // Admin / superadmin: all orders (no filter)

      if (status) query = query.eq('status', status);
      query = query.order('created_at', { ascending: false });
      query = query.range((page - 1) * limit, page * limit - 1);

      const { data, error, count } = await query;
      if (error) throw error;

      return {
        data: data || [],
        pagination: { page, limit, total: count || 0, totalPages: Math.ceil((count || 0) / limit) },
      };
    } catch (error) {
      return rejectWithValue(error.message || 'Impossible de charger les commandes');
    }
  }
);

// ── Fetch Order By ID ──
export const fetchOrderById = createAsyncThunk(
  'orders/fetchOrderById',
  async (id, { rejectWithValue }) => {
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*, order_items(*, product:products(id, name, images, price)), customer:profiles!orders_user_id_fkey(id, first_name, last_name, email, phone)')
        .eq('id', id)
        .single();

      if (error) throw error;
      return { data };
    } catch (error) {
      return rejectWithValue(error.message || 'Commande introuvable');
    }
  }
);

// ── Update Order Status ──
export const updateOrderStatus = createAsyncThunk(
  'orders/updateOrderStatus',
  async ({ id, status }, { rejectWithValue }) => {
    try {
      const { data, error } = await supabase
        .from('orders')
        .update({ status })
        .eq('id', id)
        .select('*, order_items(*)')
        .single();

      if (error) throw error;
      return { data };
    } catch (error) {
      return rejectWithValue(error.message || 'Impossible de mettre à jour le statut');
    }
  }
);

// ── Cancel Order ──
export const cancelOrder = createAsyncThunk(
  'orders/cancelOrder',
  async (id, { rejectWithValue }) => {
    try {
      const { data, error } = await supabase
        .from('orders')
        .update({ status: 'cancelled' })
        .eq('id', id)
        .select('*, order_items(*)')
        .single();

      if (error) throw error;
      return { data };
    } catch (error) {
      return rejectWithValue(error.message || "Impossible d'annuler la commande");
    }
  }
);

// ── Process Payment ──
export const processPayment = createAsyncThunk(
  'orders/processPayment',
  async (paymentData, { rejectWithValue }) => {
    try {
      // Simulate payment processing
      const { data, error } = await supabase
        .from('orders')
        .update({ payment_status: 'paid', status: 'confirmed' })
        .eq('id', paymentData.orderId)
        .select('*, order_items(*)')
        .single();

      if (error) throw error;
      return { data: { status: 'paid', order: data } };
    } catch (error) {
      return rejectWithValue(error.message || 'Échec du paiement');
    }
  }
);

const initialState = {
  orders: [],
  currentOrder: null,
  pagination: { page: 1, limit: 10, total: 0, totalPages: 0 },
  loading: false,
  error: null,
  paymentStatus: null,
};

const orderSlice = createSlice({
  name: 'orders',
  initialState,
  reducers: {
    clearError: (state) => { state.error = null; },
    clearCurrentOrder: (state) => { state.currentOrder = null; },
    clearPaymentStatus: (state) => { state.paymentStatus = null; },
  },
  extraReducers: (builder) => {
    builder
      .addCase(createOrder.pending, (state) => { state.loading = true; state.error = null; })
      .addCase(createOrder.fulfilled, (state, action) => {
        state.loading = false;
        state.currentOrder = action.payload.data;
        state.orders.unshift(action.payload.data);
      })
      .addCase(createOrder.rejected, (state, action) => { state.loading = false; state.error = action.payload; })

      .addCase(fetchOrders.pending, (state) => { state.loading = true; state.error = null; })
      .addCase(fetchOrders.fulfilled, (state, action) => {
        state.loading = false;
        state.orders = action.payload.data || [];
        state.pagination = action.payload.pagination || initialState.pagination;
      })
      .addCase(fetchOrders.rejected, (state, action) => { state.loading = false; state.error = action.payload; })

      .addCase(fetchOrderById.pending, (state) => { state.loading = true; state.error = null; })
      .addCase(fetchOrderById.fulfilled, (state, action) => { state.loading = false; state.currentOrder = action.payload.data; })
      .addCase(fetchOrderById.rejected, (state, action) => { state.loading = false; state.error = action.payload; })

      .addCase(updateOrderStatus.pending, (state) => { state.loading = true; state.error = null; })
      .addCase(updateOrderStatus.fulfilled, (state, action) => {
        state.loading = false;
        const updated = action.payload.data;
        const i = state.orders.findIndex((o) => o.id === updated.id);
        if (i !== -1) state.orders[i] = updated;
        if (state.currentOrder?.id === updated.id) state.currentOrder = updated;
      })
      .addCase(updateOrderStatus.rejected, (state, action) => { state.loading = false; state.error = action.payload; })

      .addCase(cancelOrder.pending, (state) => { state.loading = true; state.error = null; })
      .addCase(cancelOrder.fulfilled, (state, action) => {
        state.loading = false;
        const cancelled = action.payload.data;
        const i = state.orders.findIndex((o) => o.id === cancelled.id);
        if (i !== -1) state.orders[i] = cancelled;
        if (state.currentOrder?.id === cancelled.id) state.currentOrder = cancelled;
      })
      .addCase(cancelOrder.rejected, (state, action) => { state.loading = false; state.error = action.payload; })

      .addCase(processPayment.pending, (state) => { state.loading = true; state.error = null; state.paymentStatus = 'processing'; })
      .addCase(processPayment.fulfilled, (state, action) => {
        state.loading = false;
        state.paymentStatus = action.payload.data.status;
        if (action.payload.data.order) state.currentOrder = action.payload.data.order;
      })
      .addCase(processPayment.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload;
        state.paymentStatus = 'failed';
      });
  },
});

export const { clearError, clearCurrentOrder, clearPaymentStatus } = orderSlice.actions;
export default orderSlice.reducer;
